List<String> mbbsPgSpecialties = [
  "Anesthesiology",
  "Anatomy",
  "Biochemistry",
  "Community Medicine",
  "Dermatology, Venereology, and Leprosy",
  "Emergency Medicine",
  "ENT (Otorhinolaryngology)",
  "Forensic Medicine and Toxicology",
  "General Medicine",
  "General Surgery",
  "Geriatrics",
  "Microbiology",
  "Obstetrics and Gynecology (OBG)",
  "Ophthalmology",
  "Orthopedics",
  "Pediatrics",
  "Pathology",
  "Pharmacology",
  "Physical Medicine and Rehabilitation (PMR)",
  "Physiology",
  "Psychiatry",
  "Pulmonary Medicine",
  "Radio-Diagnosis",
  "Radiotherapy",
  "Sports Medicine",
  "Transfusion Medicine",
  "Tropical Medicine",
];
